-- src/test/resources/schema.sql
-- Este script creará las tablas para la base de datos H2 de prueba.
-- Se ejecuta ANTES que data.sql

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- Crear la tabla 'roles' primero
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Coincide con RoleJpaEntity.id y tu DB real
                       name VARCHAR(255) NOT NULL UNIQUE,                       -- Coincide con RoleJpaEntity.name y tu DB real
                       description VARCHAR(200)                                 -- Coincide con RoleJpaEntity.description y tu DB real
);

-- Crear la tabla 'users'
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255),
                       last_name VARCHAR(255),                                  -- Coincide con UserEntity.lastName
                       document VARCHAR(255) UNIQUE NOT NULL,                   -- Coincide con UserEntity.documentId
                       phone VARCHAR(255),                                      -- Coincide con UserEntity.phoneNumber
                       birthdate DATE,                                          -- Coincide con UserEntity.dateOfBirth
                       email VARCHAR(255) UNIQUE NOT NULL,
                       password VARCHAR(255),
                       id_rol BIGINT NOT NULL,                                  -- Columna FK que apunta a roles.id
                       FOREIGN KEY (id_rol) REFERENCES roles(id)                -- Definición de la clave foránea
);